PREFIX ns1:<http://smartcity.linkeddata.es/transport/ontology/>
PREFIX owl: <http://www.w3.org/2002/07/owl#> .

# BIKE STATIONS--------------------------------------------------------------------------

# list wikidata equivalent of bike station districts

SELECT DISTINCT ?sub ?val WHERE { 
    ?bike a ns1:BikeStation.
    ?bike ns1:hasNeighbourhood ?neighbourhood.
    ?neighbourhood ns1:hasDistrict ?sub.
    ?sub a ns1:District.
    ?sub owl:sameAs ?val.
}


# list wikidata equivalent of bike station neighbourhoods

SELECT DISTINCT ?sub ?val WHERE { 
    ?bike a ns1:BikeStation.
    ?bike ns1:hasNeighbourhood ?sub.
    ?sub a ns1:Neighbourhood.
    ?sub owl:sameAs ?val.
}

# CHARGE STATIONS--------------------------------------------------------------------------

# list wikidata equivalent of charge station districts

SELECT DISTINCT ?sub ?val WHERE { 
    ?cs a ns1:ChargeStation.
    ?cs ns1:hasNeighbourhood ?neighbourhood.
    ?neighbourhood ns1:hasDistrict ?sub.
    ?sub a ns1:District.
    ?sub owl:sameAs ?val.
}


# list wikidata equivalent of charge station neighbourhoods

SELECT DISTINCT ?sub ?val WHERE { 
    ?cs a ns1:ChargeStation.
    ?cs ns1:hasNeighbourhood ?sub.
    ?sub a ns1:Neighbourhood.
    ?sub owl:sameAs ?val.
}

#list wikidata equivalent of charge station operators

SELECT DISTINCT ?sub ?val WHERE {
    ?cs a ns1:ChargeStation.
    ?cs ns1:hasOperator ?sub.
    ?sub owl:sameAs ?val. 
}