PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
	
#Devuelve el distrito de la EDAR
SELECT DISTINCT ?district ?link 
	WHERE {
		?district rdf:type <http://base.regeneratedwater.com/purification_plant/district>
		?district <http://base.regeneratedwater.com/purification_plant> ?localizacion
		?localizacion owl:sameAs ?link 
	}
		
#Devuelve los parámetros y sus links		
SELECT DISTINCT ?parameters ?link
	WHERE {
		?localizacion rdf:type <http://base.regeneratedwater.com/parameter>
		?localizacion owl:sameAs ?link 
	}